name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
version: 0.10.3

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
        dartPluginClass: AndroidCamera
      ios:
        default_package: camera_avfoundation

dependencies:
  camera_avfoundation: 0.9.9
  camera_platform_interface: 2.3.2
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: 2.0.6
  quiver: 3.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
  plugin_platform_interface: 2.1.2
  video_player: 2.2.19
  flutter_lints: 1.0.4
